# Prérequis Python

Ce notebook indique le niveau de Python attendu dans le cours. Ce n'est pas un cours de Python : si les exemples et les petites questions ci-dessous sont immédiats, passez directement au notebook suivant.

**Conseil.** Avant d'exécuter une cellule, essayez de prévoir son résultat. Modifiez ensuite une valeur et vérifiez que vous comprenez le nouvel affichage.

## 0. Installation pour le cours

Cette étape concerne **tous les étudiants**. Elle est effectuée une seule fois, dans un terminal placé à la racine du dépôt. Il faut disposer de Python 3.11 ou d'une version plus récente. Les commandes suivantes créent un environnement virtuel (`'virtual environment'`) nommé `.venv`, indépendant des autres installations Python de la machine.

Sous macOS ou Linux :

```bash
python3 -m venv .venv
source .venv/bin/activate
```

Sous Windows, dans PowerShell :

```powershell
py -m venv .venv
.venv\Scripts\Activate.ps1
```

Puis, sur tous les systèmes :

```bash
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
python -m jupyter lab
```

Les versions de JAX, Flax et Optax utilisées dans le cours sont fixées dans `requirements.txt`. À chaque nouvelle séance, il suffit de réactiver `.venv`, puis de relancer Jupyter ; il ne faut pas recréer l'environnement. Ces commandes s'exécutent dans un terminal, et non dans une cellule du notebook.

In [1]:
import sys
import flax
import jax
import optax

print(f"Python {sys.version.split()[0]}")
print(f"JAX {jax.__version__}")
print(f"Flax {flax.__version__}")
print(f"Optax {optax.__version__}")

Python 3.13.1
JAX 0.7.0
Flax 0.10.7
Optax 0.2.5


## 1. Objets, affectations et conditions

Il faut savoir distinguer un nom, l'objet auquel il fait référence et le type de cet objet.

In [2]:
n = 5
nom = "machine affine"
active = True

if active and n > 3:
    description = f"{nom} avec {n} paramètres"
else:
    description = "machine inactive"

print(description)
print(type(n), type(nom), type(active))

machine affine avec 5 paramètres
<class 'int'> <class 'str'> <class 'bool'>


**À vérifier.** Que se passe-t-il si 'active' vaut 'False' ? Quelle différence y a-t-il entre '=' et '==' ?

## 2. Listes, tuples, indices et boucles

Un objet est **modifiable** (`'mutable'`) si son contenu peut changer sans que l'on construise un nouvel objet. Les `list` et les `dict` sont modifiables ; les nombres, les chaînes de caractères et les tuples ne le sont pas. Une affectation ne copie pas nécessairement l'objet : deux noms peuvent donc désigner la même liste. Les tuples sont notamment utiles pour regrouper des objets dont le nombre et le rôle sont fixés.

In [3]:
valeurs = [1, 2, 3, 4, 5]
point = (2.0, -1.0)

print(valeurs[0], valeurs[-1], valeurs[1:4])
print(point[0], point[1])

carres_pairs = [k**2 for k in valeurs if k % 2 == 0]
print(carres_pairs)

valeurs.append(6)
dernier = valeurs.pop()
print(f"{dernier=} {valeurs=}")

for indice, valeur in enumerate(valeurs[:3]):
    print(f"{indice=} {valeur=}")

somme = 0
for valeur in valeurs:
    somme += valeur
print(somme)

u = [1, 2]
v = u              # u et v désignent la même liste
w = u.copy()       # w désigne une nouvelle liste
v.append(3)
print(f"{u=} {v=} {w=}")

1 5 [2, 3, 4]
2.0 -1.0
[4, 16]
dernier=6 valeurs=[1, 2, 3, 4, 5]
indice=0 valeur=1
indice=1 valeur=2
indice=2 valeur=3
15
u=[1, 2, 3] v=[1, 2, 3] w=[1, 2]


**À vérifier.** Réécrivez la compréhension définissant 'carres_pairs' avec une boucle. Pourquoi 'valeurs[1:4]' ne contient-elle pas 'valeurs[4]' ? Que font 'append', 'pop' et 'enumerate' ? Enfin, expliquez pourquoi la modification faite par l'intermédiaire de `v` est également visible dans `u`, mais pas dans `w`.

## 3. Dictionnaires

Un dictionnaire associe des clés à des valeurs. Nous en utiliserons souvent pour organiser des paramètres ou des résultats.

In [4]:
parametres = {
    "largeur": 16,
    "profondeur": 3,
    "activation": "tanh",
}

print(parametres["largeur"])

for nom, valeur in parametres.items():
    print(f"{nom}: {valeur}")

parametres_modifies = {**parametres, "largeur": 32}
print(parametres)
print(parametres_modifies)

16
largeur: 16
profondeur: 3
activation: tanh
{'largeur': 16, 'profondeur': 3, 'activation': 'tanh'}
{'largeur': 32, 'profondeur': 3, 'activation': 'tanh'}


**À vérifier.** Ajoutez une clé 'pas' de valeur 0.01. Expliquez pourquoi 'parametres' et 'parametres_modifies' n'ont pas la même largeur.

## 4. Fonctions

Il faut savoir définir une fonction, lui transmettre des arguments et utiliser sa valeur de retour.

In [5]:
def erreur_quadratique(prediction, cible):
    if len(prediction) != len(cible):
        raise ValueError("prediction et cible doivent avoir la même longueur")
    erreurs = [(p - z)**2 for p, z in zip(prediction, cible)]
    return sum(erreurs) / len(erreurs)


prediction = [1.0, 2.0, 4.0]
cible = [1.5, 2.0, 3.0]
print(erreur_quadratique(prediction, cible))

0.4166666666666667


**À vérifier.** Que fait 'zip' ? Modifiez la fonction pour calculer l'erreur absolue moyenne.

## 5. Une classe très simple

Une classe regroupe des données et les opérations qui leur sont associées. Une connaissance élémentaire de 'class', '__init__', 'self' et des attributs suffit pour commencer le cours.

In [6]:
class MachineAffine:
    def __init__(self, a, b):
        self.a = a
        self.b = b

    def __call__(self, x):
        return self.a * x + self.b

    def nombre_parametres(self):
        return 2


machine = MachineAffine(a=2.0, b=-1.0)
print(machine(3.0))
print(machine.a, machine.b)
print(machine.nombre_parametres())

5.0
2.0 -1.0
2


**À vérifier.** Quel rôle joue 'self' ? Ajoutez une méthode qui modifie l'ordonnée à l'origine 'b'.

## 6. Listes Python et tableaux numériques

Une liste organise des objets Python. Un tableau numérique possède notamment une forme, un type numérique et des opérations composante par composante. JAX reprendra une grande partie de cette syntaxe.

In [7]:
import numpy as np

liste = [1.0, 2.0, 3.0]
x = np.array(liste)
y = np.array([2.0, -1.0, 4.0])
A = np.array([[1.0, 2.0, 0.0], [0.0, -1.0, 3.0]])

print(liste + liste)       # concaténation de listes
print(x + x)               # addition de tableaux
print(x * y)               # produit de Hadamard
print(A @ x)               # produit matrice-vecteur
print(A.T)                 # transposée
print(x.shape, x.dtype)
print(A.shape, A.dtype)

[1.0, 2.0, 3.0, 1.0, 2.0, 3.0]
[2. 4. 6.]
[ 2. -2. 12.]
[5. 7.]
[[ 1.  0.]
 [ 2. -1.]
 [ 0.  3.]]
(3,) float64
(2, 3) float64


**À vérifier.** Prévoyez les formes de 'A @ x' et de 'A.T' avant d'exécuter la cellule. Pourquoi 'liste + liste' et 'x + x' ne donnent-ils pas le même type de résultat ? À quoi sert 'dtype' ?

## Autoévaluation finale

Vous êtes prêt à commencer si vous savez :

- lire et modifier les cellules précédentes ;
- utiliser une liste, un tuple et un dictionnaire ;
- écrire une boucle, une condition et une fonction simple ;
- comprendre les attributs et les méthodes de 'MachineAffine' ;
- distinguer une liste Python d'un tableau numérique ;
- lire un message d'erreur et retrouver la cellule concernée.

Il n'est pas nécessaire de connaître des constructions plus avancées de Python pour commencer le cours.